###

POST http://localhost:3000/register-leader 
Content-Type: application/json

{
    "name": "mateus lima",
    "email": "mateus@gmail.com",
    "specialty": "historia"
}

###

POST http://localhost:3000/create-project 
Content-Type: application/json

{
    "name": "historia",
    "timestamp":"2025-12-05T12:00:00"
}

###

POST http://localhost:3000/enroll-project 
Content-Type: application/json

{
    "student": {
        "name": "marcos ",
        "email": "marcosbarros@gmail.com"
    },
    "leader": {
        "email": "mateus@gmail.com"
    },
    "project": {
        "name": "historia"
    },
    "timestamp":"2025-12-05T12:00:00"
}

###
GET http://localhost:3000/finder-leader?name=historia
