###

POST http://localhost:3000/register-leader 
Content-Type: application/json

{
    "name": "andreia marinho",
    "email": "andreia@gmail.com",
    "specialty": "matematica"
}

###

POST http://localhost:3000/create-project 
Content-Type: application/json

{
    "name": "matematica",
    "timestamp":"2025-12-05T12:00:00"
}

###

POST http://localhost:3000/enroll-project 
Content-Type: application/json

{
    "student": {
        "name": "marcos",
        "email": "marcos@gmail.com"
    },
    "leader": {
        "email": "andreia@gmail.com"
    },
    "project": {
        "name": "matematica"
    },
    "timestamp":"2025-12-05T12:00:00"
}

###
GET http://localhost:3000/finder-leader?name=matematica